/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface SamplePointRequest
 */
export interface SamplePointRequest {
    /**
     * 
     * @type {number}
     * @memberof SamplePointRequest
     */
    'real': number;
    /**
     * 
     * @type {number}
     * @memberof SamplePointRequest
     */
    'imag': number;
    /**
     * 
     * @type {number}
     * @memberof SamplePointRequest
     */
    'max_iterations'?: number;
}
/**
 * 
 * @export
 * @interface SamplePointResponse
 */
export interface SamplePointResponse {
    /**
     * 
     * @type {number}
     * @memberof SamplePointResponse
     */
    'iterations': number;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * CalculatorApi - axios parameter creator
 * @export
 */
export const CalculatorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Sample Point
         * @param {SamplePointRequest} samplePointRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        samplePoint: async (samplePointRequest: SamplePointRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'samplePointRequest' is not null or undefined
            assertParamExists('samplePoint', 'samplePointRequest', samplePointRequest)
            const localVarPath = `/sample_point`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(samplePointRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalculatorApi - functional programming interface
 * @export
 */
export const CalculatorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CalculatorApiAxiosParamCreator(configuration)
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Sample Point
         * @param {SamplePointRequest} samplePointRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async samplePoint(samplePointRequest: SamplePointRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SamplePointResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.samplePoint(samplePointRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CalculatorApi.samplePoint']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CalculatorApi - factory interface
 * @export
 */
export const CalculatorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CalculatorApiFp(configuration)
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Sample Point
         * @param {SamplePointRequest} samplePointRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        samplePoint(samplePointRequest: SamplePointRequest, options?: any): AxiosPromise<SamplePointResponse> {
            return localVarFp.samplePoint(samplePointRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CalculatorApi - object-oriented interface
 * @export
 * @class CalculatorApi
 * @extends {BaseAPI}
 */
export class CalculatorApi extends BaseAPI {
    /**
     * Ping the server to check if it is running.
     * @summary Sample Point
     * @param {SamplePointRequest} samplePointRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalculatorApi
     */
    public samplePoint(samplePointRequest: SamplePointRequest, options?: RawAxiosRequestConfig) {
        return CalculatorApiFp(this.configuration).samplePoint(samplePointRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TestsApi - axios parameter creator
 * @export
 */
export const TestsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingAPI: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TestsApi - functional programming interface
 * @export
 */
export const TestsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TestsApiAxiosParamCreator(configuration)
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingAPI(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingAPI(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TestsApi.pingAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TestsApi - factory interface
 * @export
 */
export const TestsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TestsApiFp(configuration)
    return {
        /**
         * Ping the server to check if it is running.
         * @summary Ping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingAPI(options?: any): AxiosPromise<boolean> {
            return localVarFp.pingAPI(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TestsApi - object-oriented interface
 * @export
 * @class TestsApi
 * @extends {BaseAPI}
 */
export class TestsApi extends BaseAPI {
    /**
     * Ping the server to check if it is running.
     * @summary Ping
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TestsApi
     */
    public pingAPI(options?: RawAxiosRequestConfig) {
        return TestsApiFp(this.configuration).pingAPI(options).then((request) => request(this.axios, this.basePath));
    }
}



